name: Benchmark

on: [push, pull_request]

jobs:
  benchmark:
    name: ${{ matrix.os }} - ${{ matrix.rust }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [stable, nightly, 1.45.2]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
      - run: git checkout HEAD~1
      - run: cargo bench
      - run: git checkout -
      - run: cargo bench
